/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ChatInput: React.FC = () => {
  return (
    <form className="flex gap-5 justify-between px-5 py-3.5 mt-5 text-xl bg-gray-200 rounded-md text-zinc-500 text-opacity-60 max-md:flex-wrap max-md:pl-5 max-md:mt-10 max-md:max-w-full">
      <label htmlFor="chatInput" className="sr-only">
        Type your message
      </label>
      <input
        type="text"
        id="chatInput"
        placeholder="Type Here"
        className="bg-transparent border-none outline-none flex-grow"
      />
      <button type="submit" aria-label="Send message">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b420a9b4d5d9a10678adf4752aa4a128fe4a8aac67857693b299bfb21ad70060?apiKey=79050f2e54364c9b998b189296d8e734&"
          alt=""
          className="shrink-0 self-start w-5 aspect-square"
        />
      </button>
    </form>
  );
};

export default ChatInput;
