/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ChatMessage from "./ChatMessage";
import ChatInput from "./ChatInput";

const ChatSection: React.FC = () => {
  const messages = [
    { type: "assistant", content: "How can I help you today!" },
    {
      type: "user",
      content:
        "Hi there! I'm planning for a personalised trip and need some information about a tourist place. Can you help me?",
    },
    {
      type: "assistant",
      content:
        "Of course! I'd be happy to help. Which tourist place are you interested in?",
    },
    {
      type: "user",
      content:
        "I'm thinking of visiting Chennai. What are some must-see attractions there?",
    },
    {
      type: "assistant",
      content:
        "Chennai is a vibrant city with a rich cultural heritage. Some must-see attractions include Marina Beach, Kapaleeshwarar Temple, Fort St. George, and the Government Museum. Are you interested in anything specific, like history, culture, or maybe food?",
    },
    {
      type: "user",
      content:
        "I'm really into culture and historical sites. What would you recommend?",
    },
    {
      type: "user",
      content:
        "I'm really into culture and historical sites. What would you recommend?",
    },
    {
      type: "user",
      content:
        "I'm really into culture and historical sites. What would you recommend?",
    },
    {
      type: "user",
      content:
        "Hi there! I'm planning for a personalised trip and need some information about a tourist place. Can you help me?",
    },
    {
      type: "assistant",
      content:
        "Of course! I'd be happy to help. Which tourist place are you interested in?",
    },
    {
      type: "user",
      content:
        "I'm thinking of visiting Chennai. What are some must-see attractions there?",
    },
    {
      type: "assistant",
      content:
        "Chennai is a vibrant city with a rich cultural heritage. Some must-see attractions include Marina Beach, Kapaleeshwarar Temple, Fort St. George, and the Government Museum. Are you interested in anything specific, like history, culture, or maybe food?",
    },
    {
      type: "user",
      content:
        "I'm really into culture and historical sites. What would you recommend?",
    },
    {
      type: "user",
      content:
        "I'm really into culture and historical sites. What would you recommend?",
    },
    {
      type: "user",
      content:
        "I'm really into culture and historical sites. What would you recommend?",
    },
    {
      type: "assistant",
      content:
        "Chennai is a vibrant city with a rich cultural heritage. Some must-see attractions include Marina Beach, Kapaleeshwarar Temple, Fort St. George, and the Government Museum. Are you interested in anything specific, like history, culture, or maybe food?",
    },
    {
      type: "user",
      content:
        "I'm really into culture and historical sites. What would you recommend?",
    },
    {
      type: "user",
      content:
        "I'm really into culture and historical sites. What would you recommend?",
    },
    {
      type: "user",
      content:
        "I'm really into culture and historical sites. What would you recommend?",
    },
    {
      type: "user",
      content:
        "Hi there! I'm planning for a personalised trip and need some information about a tourist place. Can you help me?",
    },
    {
      type: "assistant",
      content:
        "Of course! I'd be happy to help. Which tourist place are you interested in?",
    },
    {
      type: "user",
      content:
        "I'm thinking of visiting Chennai. What are some must-see attractions there?",
    },
    {
      type: "assistant",
      content:
        "Chennai is a vibrant city with a rich cultural heritage. Some must-see attractions include Marina Beach, Kapaleeshwarar Temple, Fort St. George, and the Government Museum. Are you interested in anything specific, like history, culture, or maybe food?",
    },
    {
      type: "user",
      content:
        "I'm really into culture and historical sites. What would you recommend?",
    },
    {
      type: "user",
      content:
        "I'm really into culture and historical sites. What would you recommend?",
    },
    {
      type: "user",
      content:
        "I'm really into culture and historical sites. What would you recommend?",
    },
 
  ];

  return (
    <div className="flex flex-col w-1/2 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col p-6 text-base leading-7 text-black rounded-xl border border-solid border-[#9AAC47] border-opacity-30 max-md:px-5 max-md:mt-5 max-md:max-w-full overflow-hidden mb-5 h-full">
        <div className="overflow-hidden-vertical">
        {messages.map((message, index) => (
          <div
            key={index}
            className={`flex ${
              message.type === "user" ? "justify-start" : "justify-start"
            }`}
          >
            <ChatMessage
              type={message.type}
              content={message.content}
            />
          </div>
        ))}
        </div>
        <div className="">
        <ChatInput />
        </div>
      </div>
    </div>
  );
};

export default ChatSection;
