/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ChatMessageProps {
  type: string;
  content: string;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ type, content }) => {
  const isAssistant = type === "assistant";
  const containerClasses = isAssistant
    ? "flex p-5 rounded-xl almond-green bg-opacity-20 max-md:flex-wrap"
    : "flex p-5 rounded-xl max-md:flex-wrap";
  const iconSrc = isAssistant
    ? "https://cdn.builder.io/api/v1/image/assets/TEMP/de388b7f96e10b477b2eba6351b931cb790bbbfe31c6f94b946f2f923264b707?apiKey=79050f2e54364c9b998b189296d8e734&"
    : "";

  return (
    <div className={containerClasses}>
      {isAssistant && (
        <img
          loading="lazy"
          src={iconSrc}
          alt="Assistant icon"
          className="shrink-0 my-auto w-5 aspect-square"
        />
      )}
      <div className={isAssistant ? "max-md:max-w-full" : ""}>{content}</div>
    </div>
  );
};

export default ChatMessage;
