/**
 * This code was generated by Builder.io.
 */
import React from "react";

const DaySelector: React.FC = () => {
  return (
    <div className="flex gap-2 self-start text-sm tracking-tight text-[#9AAC47]">
      <button className="justify-center px-7 py-2 text-white bg-[#9AAC47] rounded-3xl border border-[#9AAC47] border-solid max-md:px-5">
        Day 1
      </button>
      <button className="justify-center px-7 py-2 rounded-3xl border border-[#9AAC47] border-solid max-md:px-5">
        Day 2
      </button>
      <button className="justify-center px-7 py-2 rounded-3xl border border-[#9AAC47] border-solid max-md:px-5">
        Day 3
      </button>
    </div>
  );
};

export default DaySelector;
