/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <div className="flex gap-5 justify-between w-full max-md:flex-wrap max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/ec0ce476413740599f107b75e9e191a9c87efbbd2b42b5b57e9c7d48e32b8d2b?apiKey=79050f2e54364c9b998b189296d8e734&"
        alt="Logo"
        className="shrink-0 max-w-full aspect-[2.38] w-[118px]"
      />
      <div className="flex gap-4 my-auto" />
    </div>
  );
};

export default Header;
