/**
 * This code was generated by Builder.io.
 */
import React from "react";
import DaySelector from "./DaySelector";
import ItineraryItem from "./ItineraryItem";

const ItinerarySection: React.FC = () => {
  const itineraryItems = [
    {
      title: "Murugan Idli Shop",
      time: "8.00 AM",
      description:
        "Murugan Idli Shop in Chennai (Madras) is a hidden gem for food enthusiasts like you.",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/ed4c01987fdbb7d2ff84b157debc30a129ea5b816b99de7e2af2c951bfbaadb0?apiKey=79050f2e54364c9b998b189296d8e734&",
    },
    {
      title: "Kamakshi Amman Temple",
      time: "9.00 AM",
      description:
        "Located in Chennai (Madras), the Kamakshi Amman Temple is a sacred Hindu temple.....",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/0e8e9e9c0c1492c46bdc72f8eaef59cc6fc94557ddf1574217a065bd969b97c0?apiKey=79050f2e54364c9b998b189296d8e734&",
    },
    {
      title: "National Art Gallery",
      time: "11.00 AM",
      description:
        "The National Art Gallery in Chennai (Madras) is a treasure trove for art enthusiasts like you.",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/e36ba4fd7c490d5c90a8a8a389949ba71c618e33c63c31d005abc86b94c9f98b?apiKey=79050f2e54364c9b998b189296d8e734&",
    },
    {
      title: "The Dakshin Restaurant",
      time: "2.00 AM",
      description:
        "The Dakshin Restaurant in Chennai offers exceptional South Indian cuisine, representi.....",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/79759a263be8d9ef07e01f787461cb748e4c1d521541de78169cb6fd83d57b33?apiKey=79050f2e54364c9b998b189296d8e734&",
    },
    {
      title: "Kapaleeshwarar Temple",
      time: "5.00 AM",
      description:
        "Kapaleeshwarar Temple in Chennai (Madras) is a stunning example of Dravidian architect.....",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/c495533d7b40d0318300df803dc8e79e36c10605225cc06af9e78c1682a95004?apiKey=79050f2e54364c9b998b189296d8e734&",
    },
  ];

  return (
<div className="flex flex-col w-1/2 max-md:ml-0 max-md:w-full">
<div className="flex flex-col p-6 text-base leading-7 text-black rounded-xl border border-solid border-[#9AAC47] border-opacity-30 max-md:px-5 max-md:mt-5 max-md:max-w-full overflow-hidden mb-5 h-full">
          <DaySelector />
          {itineraryItems.map((item, index) => (
            <ItineraryItem key={index} {...item} />
          ))}
        </div>
      </div>
  );
};

export default ItinerarySection;
