/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import ChatSection from "./ChatSection";
import ItinerarySection from "./ItinerarySection";

const TripPlanner: React.FC = () => {
  return (
    <div className="flex flex-col px-12 py-14 bg-neutral-100 max-md:px-5 h-screen shrink-0">
      <Header />
      <div className="mt-11 max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col max-md:gap-0">
          <ChatSection />
          <ItinerarySection />
        </div>
      </div>
    </div>
  );
};

export default TripPlanner;
